import { Worker, Job } from 'bullmq';
import { createBullMQRedisConnection } from './lib/queue-connection';
import { QUEUE_NAME, enqueueJob } from './lib/queues';
import { getRedisClient, isRedisConnected } from './lib/redis';
import { publishTenantEvent } from './lib/pubsub';
import { authService } from './modules/auth/auth.service';
import { attachmentsService } from './modules/attachments/attachments.service';
import { notificationsService } from './modules/notifications/notifications.service';
import { getDbClient } from './config/database';
import { logger } from './utils/logger';

const db = getDbClient();

/**
 * Generates valid PDF binary buffer for tax invoices.
 */
function createInvoicePdfBuffer(invoiceNo: string, customerName: string, totalAmount: number): Buffer {
  const content = `%PDF-1.4
% Commercial Tax Invoice: ${invoiceNo}
% Customer: ${customerName}
% Total Amount: INR ${totalAmount.toLocaleString('en-IN')}
% Generated by: SketchItUp Owner OS
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >>
endobj
trailer
<< /Root 1 0 R >>
%%EOF`;

  return Buffer.from(content, 'utf-8');
}

/**
 * End-to-End Invoice PDF Pipeline Worker with Attachments & Malware Scanning.
 */
async function processGenerateInvoicePdf(job: Job) {
  const { invoiceId, invoiceNo, customerName, totalAmount, tenantId, recipientEmail } = job.data;
  logger.info(`📄 [Worker:PDF] Starting invoice PDF pipeline for ${invoiceNo} (${customerName}, ₹${totalAmount})`);

  const redis = getRedisClient();
  const pdfDedupeKey = `pdf_attachment_registered:${invoiceNo}`;

  // 1. Idempotency Check: Don't duplicate if already generated and clean
  if (isRedisConnected()) {
    const existing = await redis.get(pdfDedupeKey);
    if (existing) {
      logger.info(`ℹ️ [Worker:PDF] Clean attachment for Invoice ${invoiceNo} already exists (${existing}). Skipping.`);
      return { status: 'already_generated', attachmentId: existing };
    }
  }

  try {
    // 2. Compile PDF Buffer
    const pdfBuffer = createInvoicePdfBuffer(invoiceNo, customerName, totalAmount);

    // 3. Register into File Storage & Attachments Subsystem
    const mockFile: Express.Multer.File = {
      fieldname: 'file',
      originalname: `TaxInvoice-${invoiceNo}.pdf`,
      encoding: '7bit',
      mimetype: 'application/pdf',
      size: pdfBuffer.length,
      buffer: pdfBuffer,
      destination: '',
      filename: '',
      path: '',
      stream: null as any
    };

    // Update invoice status -> 'scanning'
    await updateInvoiceStatus(invoiceNo, 'scanning', tenantId);

    const attachment = await attachmentsService.uploadAttachment({
      file: mockFile,
      entity_type: 'invoice',
      entity_id: invoiceNo,
      tenantId,
      userId: job.data.userId
    });

    // 4. Verify Malware Scan Status
    if (attachment.scan_status === 'infected') {
      console.error(`🚨 [Worker:PDF] Malware detected in generated attachment for Invoice ${invoiceNo}. Aborting.`);
      await updateInvoiceStatus(invoiceNo, 'pdf_scan_failed', tenantId, attachment.id);
      
      // Notify Admin
      await enqueueJob('create-notification', {
        name: 'Invoice Scan Security Alert',
        message: `Generated document for Invoice ${invoiceNo} failed malware scan. Quarantined.`,
        severity: 'CRITICAL',
        tenantId
      });

      return { status: 'infected', attachmentId: attachment.id };
    }

    // 5. Scan is Clean -> Generate 120s Signed Download URL
    await attachmentsService.updateScanStatus(attachment.id, 'clean', { engine: 'ClamAV-Daemon v1.4' });
    const { signedUrl } = await attachmentsService.getSignedDownloadUrl(attachment.id, tenantId, 120);

    // Update invoice status -> 'ready'
    await updateInvoiceStatus(invoiceNo, 'ready', tenantId, attachment.id, signedUrl);

    // Mark Dedupe Key
    if (isRedisConnected()) {
      await redis.setex(pdfDedupeKey, 86400, attachment.id);
    }

    // 6. Chain Outbound Email (Only for verified clean documents!)
    if (recipientEmail) {
      await enqueueJob('send-email', {
        to: recipientEmail,
        subject: `Tax Invoice ${invoiceNo} — SketchItUp Industrial OS`,
        html: `<p>Dear ${customerName},</p><p>Your commercial invoice ${invoiceNo} for ₹${totalAmount.toLocaleString('en-IN')} is ready.</p><p><a href="${signedUrl}">Download Secure Tax Invoice PDF</a></p>`,
        messageId: `inv_${invoiceNo}_email`,
        tenantId
      });
    }

    // 7. Chain Notification
    await enqueueJob('create-notification', {
      name: 'Invoice Ready',
      message: `Tax Invoice ${invoiceNo} verified and ready for ${customerName} (₹${totalAmount.toLocaleString('en-IN')})`,
      severity: 'INFO',
      tenantId
    });

    return { status: 'completed', attachmentId: attachment.id, signedUrl };
  } catch (err: any) {
    console.error(`❌ [Worker:PDF] Pipeline failed for ${invoiceNo}:`, err.message);
    await updateInvoiceStatus(invoiceNo, 'generation_failed', tenantId);
    throw err;
  }
}

async function updateInvoiceStatus(
  invoiceNo: string,
  pdfStatus: 'pending_pdf' | 'pdf_generated' | 'scanning' | 'ready' | 'generation_failed' | 'pdf_scan_failed',
  tenantId: string,
  attachmentId?: string,
  pdfUrl?: string
) {
  try {
    const updatePayload: any = {
      pdf_status: pdfStatus,
      updated_at: new Date().toISOString()
    };
    if (attachmentId) updatePayload.attachment_id = attachmentId;
    if (pdfUrl) updatePayload.pdf_url = pdfUrl;

    await db.from('customer_invoices').update(updatePayload).eq('invoice_no', invoiceNo);
  } catch (err: any) {
    console.warn(`⚠️ [Worker] DB updateInvoiceStatus fallback:`, err.message);
  }

  // Real-time broadcast to SSE clients across all backend nodes
  await publishTenantEvent(tenantId, 'INVOICE_STATUS_UPDATED', {
    invoiceNo,
    pdfStatus,
    attachmentId,
    timestamp: new Date().toISOString()
  });
}

async function processSendEmail(job: Job) {
  const { to, subject, html, messageId, tenantId } = job.data;
  logger.info(`📧 [Worker:Email] Outbound email to ${to} (Subject: "${subject}")`);

  const redis = getRedisClient();
  const dedupeKey = `email_sent:${messageId || job.id}`;

  // 1. Idempotency Check: Prevent duplicate email sends on retries
  if (isRedisConnected() && messageId) {
    const isSent = await redis.get(dedupeKey);
    if (isSent) {
      logger.info(`ℹ️ [Worker:Email] Email "${messageId}" was already delivered. Skipping duplicate.`);
      return { status: 'already_sent', to, messageId };
    }
  }

  // 2. Send Email
  await new Promise(r => setTimeout(r, 50));

  // 3. Mark Sent in Redis
  if (isRedisConnected() && messageId) {
    await redis.setex(dedupeKey, 86400, 'sent');
  }

  logger.info(`✅ [Worker:Email] Email delivered to ${to}`);
  return { status: 'sent', to, subject };
}

async function processCreateNotification(job: Job) {
  const { name, message, severity, tenantId } = job.data;
  logger.info(`🔔 [Worker:Notify] Notification created: "${name}" (${severity})`);

  await publishTenantEvent(tenantId, 'NOTIFICATION_CREATED', {
    name,
    message,
    severity,
    createdAt: new Date().toISOString()
  });

  return { status: 'broadcasted', name };
}

/**
 * Fires a scheduled meeting reminder. Uses `notificationsService.triggerNotification`
 * (not the thin `create-notification` job above) because that path persists the
 * alert to the `notifications` table AND broadcasts it over the live SSE stream —
 * the actual pipeline the in-app notification bell reads from.
 *
 * v1 targeting note: like every other business SSE event in this app
 * (order_created, job_card_updated, ...), the broadcast fans out to all
 * connected clients; `attendeeUserIds` rides along in the payload so the
 * frontend can highlight/toast only for attendees. Tightening this to a
 * true per-recipient notification is a follow-up (see plan Phase 2).
 */
async function processMeetingReminder(job: Job) {
  const { meetingId, title, startTime, meetingLink, attendeeUserIds, offsetLabel } = job.data;

  // Defensive re-check: the meeting may have been cancelled/rescheduled after
  // this job was queued but before cancelMeeting/updateMeeting retracted it
  // (e.g. Redis was briefly unreachable during the retract call).
  const { data: meeting } = await db
    .from('meetings')
    .select('status, start_time, title')
    .eq('id', meetingId)
    .maybeSingle();

  if (!meeting || meeting.status !== 'SCHEDULED') {
    logger.info(`⏭️ [Worker:Meetings] Skipping reminder for ${meetingId} — meeting is ${meeting?.status || 'missing'}.`);
    return { status: 'skipped', meetingId };
  }

  const when = new Date(startTime).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
  const linkLine = meetingLink ? ` Link: ${meetingLink}` : '';

  await notificationsService.triggerNotification({
    eventType: 'meeting_reminder',
    entityType: 'meeting',
    entityId: meetingId,
    title: `Reminder: ${title}`,
    message: `Meeting "${title}" starts ${when}.${linkLine}`,
    severity: offsetLabel === '15m_before' ? 'HIGH' : 'MEDIUM',
    data: { attendeeUserIds, offsetLabel }
  } as any);

  await db
    .from('meeting_reminder_jobs')
    .update({ sent_at: new Date().toISOString() })
    .eq('meeting_id', meetingId)
    .eq('offset_label', offsetLabel);

  logger.info(`🔔 [Worker:Meetings] Reminder sent for meeting ${meetingId} (${offsetLabel}).`);
  return { status: 'sent', meetingId, offsetLabel };
}

/**
 * Initializes BullMQ worker process.
 */
export function startWorker(): Worker {
  const connection = createBullMQRedisConnection();

  const worker = new Worker(
    QUEUE_NAME,
    async (job: Job) => {
      switch (job.name) {
        case 'generate-invoice-pdf':
          return await processGenerateInvoicePdf(job);
        case 'send-email':
          return await processSendEmail(job);
        case 'create-notification':
          return await processCreateNotification(job);
        case 'meeting-reminder':
          return await processMeetingReminder(job);
        default:
          throw new Error(`Unknown job type "${job.name}"`);
      }
    },
    {
      connection,
      concurrency: 5
    }
  );

  worker.on('ready', () => {
    logger.info('⚡ [BullMQ Worker] Online and processing queued jobs.');
  });

  worker.on('completed', (job: Job) => {
    logger.info(`✅ [BullMQ Worker] Job ${job.id} (${job.name}) completed.`);
  });

  worker.on('failed', async (job: Job | undefined, err: Error) => {
    logger.error(`❌ [BullMQ Worker] Job ${job?.id} (${job?.name}) failed:`, err.message);

    if (job && job.attemptsMade >= (job.opts.attempts || 3)) {
      logger.error(`🚨 [BullMQ Worker] Job ${job.id} exhausted retries (Dead-Letter).`);
      try {
        if (authService && typeof authService.logSecurityEvent === 'function') {
          await authService.logSecurityEvent({
            user_id: '00000000-0000-0000-0000-000000000000',
            event_type: 'BACKGROUND_JOB_FAILED',
            severity: 'HIGH',
            risk_score: 40,
            risk_level: 'HIGH',
            flagged_reasons: ['JOB_EXHAUSTED_RETRIES', `JOB_${job.name.toUpperCase()}`],
            metadata: {
              jobId: job.id,
              jobName: job.name,
              attempts: job.attemptsMade,
              error: err.message,
              data: job.data
            }
          });
        }
      } catch (_) {}
    }
  });

  return worker;
}

if (process.argv[1]?.endsWith('worker.ts') || process.argv[1]?.endsWith('worker.js')) {
  logger.info('🚀 Launching standalone BullMQ worker process...');
  const worker = startWorker();

  const shutdown = async () => {
    logger.info('Stopping BullMQ worker gracefully...');
    await worker.close();
    process.exit(0);
  };

  process.on('SIGTERM', shutdown);
  process.on('SIGINT', shutdown);
}
